// SPDX-License-Identifier: CC0-1.0
// SPDX-FileCopyrightText: No rights reserved

import eslint from '@eslint/js';
import { defineConfig } from '@eslint/config-helpers';
import globals from 'globals';
import jsdoc from 'eslint-plugin-jsdoc';
import prettier from 'eslint-plugin-prettier';
import prettierConfig from 'eslint-config-prettier';
import tseslint from 'typescript-eslint';

const __dirname = import.meta.dirname;

export default defineConfig([
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  jsdoc.configs['flat/recommended'],
  prettierConfig,
  {
    files: ['**/*.ts', '**/*.js'],
    plugins: {
      jsdoc,
      prettier,
      '@typescript-eslint': tseslint.plugin,
    },
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parser: tseslint.parser,
      parserOptions: {
        sourceType: 'module',
        project: 'tsconfig.gnome45.json',
        tsconfigRootDir: __dirname,
        warnOnUnsupportedTypeScriptVersion: false,

      },
      globals: {
        ARGV: 'readonly',
        Debugger: 'readonly',
        GIRepositoryGType: 'readonly',
        globalThis: 'readonly',
        imports: 'readonly',
        Intl: 'readonly',
        log: 'readonly',
        logError: 'readonly',
        pkg: 'readonly',
        print: 'readonly',
        printerr: 'readonly',
        window: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        global: 'readonly',
        _: 'readonly',
        C_: 'readonly',
        N_: 'readonly',
        ngettext: 'readonly',
      },
    },
    settings: {
      jsdoc: {
        mode: 'typescript',
        tagNamePreference: {
          returns: 'returns',
          param: 'param',
        },
      },
    },
    rules: {
      'prettier/prettier': 'error',
      'array-callback-return': 'error',
      'no-await-in-loop': 'error',
      'no-constant-binary-expression': 'error',
      'no-constructor-return': 'error',
      'no-new-native-nonconstructor': 'error',
      'no-promise-executor-return': 'error',
      'no-self-compare': 'error',
      'no-template-curly-in-string': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unreachable-loop': 'error',
      'no-unused-private-class-members': 'error',
      'no-use-before-define': [
        'error',
        {
          functions: false,
          classes: true,
          variables: true,
          allowNamedExports: true,
        },
      ],
      'block-scoped-var': 'error',
      'complexity': 'warn',
      'consistent-return': 'error',
      'default-param-last': 'error',
      'eqeqeq': 'error',
      'no-array-constructor': 'error',
      'no-caller': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-iterator': 'error',
      'no-label-var': 'error',
      'no-loop-func': 'error',
      'no-multi-assign': 'error',
      'no-new-object': 'error',
      'no-new-wrappers': 'error',
      'no-proto': 'error',
      'no-shadow': 'off',
      'no-shadow-restricted-names': 'error',
      'no-unused-vars': 'off',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-return': 'error',
      'no-with': 'error',
      'unicode-bom': 'error',
      'yoda': 'error',
      'array-bracket-newline': ['error', 'consistent'],
      'array-bracket-spacing': ['error', 'never'],
      'arrow-parens': ['error', 'as-needed'],
      'arrow-spacing': 'error',
      'block-spacing': ['error', 'always'],
      'brace-style': 'off',
      'comma-dangle': ['error', {
        arrays: 'always-multiline',
        objects: 'always-multiline',
        imports: 'always-multiline',
        functions: 'never',
      }],
      'comma-spacing': ['error', {
        before: false,
        after: true,
      }],
      'comma-style': [
        'error',
        'last',
      ],
      'computed-property-spacing': ['error', 'never'],
      'dot-location': ['error', 'property'],
      'eol-last': 'error',
      'func-call-spacing': 'off',
      'indent': 'off',
      'key-spacing': 'off',
      'keyword-spacing': 'off',
      'linebreak-style': ['error', 'unix'],
      'lines-between-class-members': ['error', 'always'],
      'max-nested-callbacks': ['error', { max: 4 }],
      'max-statements-per-line': ['error', { max: 1 }],
      'new-parens': 'error',
      'no-mixed-operators': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'no-multi-spaces': 'off',
      'no-multiple-empty-lines': ['error', { max: 2, maxEOF: 1, maxBOF: 0 }],
      'no-trailing-spaces': 'error',
      'no-whitespace-before-property': 'error',
      'object-curly-newline': ['error', { consistent: true }],
      'object-curly-spacing': 'off',
      'operator-linebreak': ['error'],
      'padded-blocks': ['error', 'never'],
      'quotes': 'off',
      'rest-spread-spacing': ['error', 'never'],
      'semi': 'off',
      'semi-spacing': ['error', { before: false, after: true }],
      'semi-style': ['error', 'last'],
      'space-before-blocks': 'off',
      'space-before-function-paren': 'off',
      'space-in-parens': ['error', 'never'],
      'space-infix-ops': 'off',
      'space-unary-ops': ['error', { words: false, nonwords: false }],
      'switch-colon-spacing': ['error', { after: true, before: false }],
      'template-curly-spacing': ['error', 'never'],
      'template-tag-spacing': ['error', 'never'],
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          vars: 'all',
          args: 'none',
          ignoreRestSiblings: false,
          varsIgnorePattern: '^_',
          argsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-module-boundary-types': 'off',
      '@typescript-eslint/no-shadow': 'error',
      'jsdoc/check-alignment': 'error',
      'jsdoc/check-param-names': 'error',
      'jsdoc/check-property-names': 'error',
      'jsdoc/check-tag-names': 'error',
      'jsdoc/check-types': 'off',
      'jsdoc/check-values': 'error',
      'jsdoc/empty-tags': 'error',
      'jsdoc/implements-on-classes': 'error',
      'jsdoc/multiline-blocks': 'error',
      'jsdoc/no-multi-asterisks': ['error', { allowWhitespace: true }],
      'jsdoc/no-undefined-types': 'off',
      'jsdoc/require-description': 'off',
      'jsdoc/require-description-complete-sentence': 'off',
      'jsdoc/require-jsdoc': [
        'warn',
        {
          require: {
            FunctionDeclaration: true,
            MethodDefinition: true,
            ClassDeclaration: true,
            ArrowFunctionExpression: false,
            FunctionExpression: false,
          },
          publicOnly: true,
        },
      ],
      'jsdoc/require-param': 'off',
      'jsdoc/require-param-description': 'off',
      'jsdoc/require-param-name': 'error',
      'jsdoc/require-param-type': 'off',
      'jsdoc/require-property': 'off',
      'jsdoc/require-property-description': 'off',
      'jsdoc/require-property-name': 'error',
      'jsdoc/require-property-type': 'off',
      'jsdoc/require-returns': 'off',
      'jsdoc/require-returns-check': 'off',
      'jsdoc/require-returns-description': 'off',
      'jsdoc/require-returns-type': 'off',
      'jsdoc/require-yields': 'error',
      'jsdoc/require-yields-check': 'error',
      'jsdoc/tag-lines': ['error', 'any', { startLines: 1 }],
      'jsdoc/valid-types': 'off',
    },
  },
  {
    files: ['**/prefs.js', '**/prefs.ts'],
    languageOptions: {
      globals: {
        ...globals.browser,
      },
    },
    rules: {
      // Les prefs peuvent utiliser Gtk, pas Shell
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/shell*', '**/st*', '**/meta*', '**/clutter*'],
              message: 'Shell imports are not allowed in preferences.',
            },
          ],
        },
      ],
    },
  },
  {
    files: ['**/extension.js', '**/extension.ts'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['**/gtk*'],
              message: 'GTK imports are not allowed in the shell process.',
            },
          ],
        },
      ],
    },
  },
  {
    ignores: [
      'node_modules/**',
      'build/**',
      'dist/**',
      'packages/**',
      '**/*.d.ts',
      '@types/**',
      'types/**',
      'schemas/**/*.xml',
      '.scripts/**',
      'eslint.config.js'
    ],
  },
]);
